config:
  # Change this variable to be unique within your apps (don't change for the same app)
  app-name:  noteit
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, dev}
  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  environmentSecrets: ${file(env.yml):${self:custom.stage}, file(env.yml):default}
  # Provider configs
  provider:
    name: aws
    runtime: nodejs8.10

    # Change this according to the stage in which you are developing
    stage: dev
    region: eu-west-2
