service: ${file(../../config.yml):custom.provider.app-name}-dynamodb

custom:
  tableThroughputs:
    # When stage is defined as prod on config.yml
    prod: 5
    # For every other development stage
    default: 1

provider:
  name: ${file(../../config.yml):custom.provider.name}
  runtime: ${file(../../config.yml):custom.provider.runtime}
  stage: ${file(../../config.yml):custom.provider.stage}
  region: ${file(../../config.yml):custom.provider.region}
  # Set the table name here so we can use it while testing locally
  tableName: ${file(../../config.yml):custom.provider.stage}-${file(../../config.yml):custom.appname}-notes
  tableThroughput: ${self:custom.tableThroughputs.${file(../../config.yml):custom.provider.stage}, self:custom.tableThroughputs.default}

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:provider.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        # Set the capacity based on the stage
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:provider.tableThroughput}
          WriteCapacityUnits: ${self:provider.tableThroughput}

  Outputs:
    NotesTableArn:
      Value:
        Fn::GetAtt:
          - NotesTable
          - Arn
      Export:
        Name: ${file(../../config.yml):custom.provider.stage}-NotesTableArn
