# It's important that this part is always the same for all services in the app, for each deploy
# Except for the environment variables, that can be different
config:
  # Change this variable to be unique within your apps (don't change for the same app)
  app-name: noteit
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, dev}

  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  # Uncomment when needed
  # environmentSecrets: ${file(env.yml):${self:config.stage}, file(env.yml):default}

  # Provider configs
  provider:
    name: aws
    runtime: nodejs8.10

    # Change this according to the stage in which you are developing
    stage: dev
    region: eu-west-2

service: ${self:config.app-name}-s3

provider:
  name: ${self:config.provider.name}
  runtime: ${self:config.provider.runtime}

  # Change this according to the stage in which you are developing
  stage: ${self:config.provider.stage}
  region: ${self:config.provider.region}

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

  # Print out the name of the bucket that is created
  Outputs:
    AttachmentsBucketArn:
      Value:
        Fn::GetAtt:
          - S3Bucket
          - Arn
      Export:
        Name: ${self:config.stage}-AttachmentsBucketArn

    AttachmentsBucketName:
      Value:
        Ref: S3Bucket
      Export:
        Name: ${self:config.stage}-AttachmentsBucket